name = "blackroad-services"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
workers_dev = true

routes = [
  { pattern = "mcp.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "mesh.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "cloud.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "drive.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "stream.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "cece.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "os.blackroad.io/*", zone_name = "blackroad.io" },
  { pattern = "research.blackroad.io/*", zone_name = "blackroad.io" }
]
